"""Correcting a letter in the models file

Revision ID: ebd20a301385
Revises: 092fc76d2233
Create Date: 2026-04-25 17:33:42.315486

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ebd20a301385'
down_revision: Union[str, Sequence[str], None] = '092fc76d2233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('address', sa.String(), nullable=False))
    op.drop_column('warehouses', 'adress')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('warehouses', sa.Column('adress', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('warehouses', 'address')
    # ### end Alembic commands ###
